version: '3.8'

services:
  
  # Microservicio de Catálogo
  ms-catalogo:
    build:
      context: ..
    container_name: ms-catalogo
    ports:
      - "5001:5001"  # El contenedor expone el puerto 5001
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true