services:
  
  # Microservicio de Catálogo
  ms-catalogo:
    image: mscatalogo:v1.0
    container_name: ms-catalogo
    depends_on:
      - ecommerce_app
    ports:
      - 5001:5000
    networks:
      - ecommerce_network
    environment:
      - FLASK_CONTEXT=${FLASK_CONTEXT}
      - DEV_DB_URI=${DEV_DB_URI}

networks:
  ecommerce_network:
    external: true